<a href="https://colab.research.google.com/github/FabriceGhislain7/gdr-web-app/blob/develop/statistics/data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis del Gioco di Ruolo

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
print("Librerie importate con successo.")

Librerie importate con successo.

In [3]:
# Caricamento del dataset
from urllib.error import URLError

# Inizializza la variabile data
data = None


try:
    # Controllo se il file esiste localmente
    if os.path.exists('data/big_dataset_gioco.csv'):
        data = pd.read_csv('data/big_dataset_gioco.csv')
        print("Dataset caricato dal repository del progetto gdr-web-app")

    # Controllo se il file esiste in Google Colab e lo carico
    elif os.path.exists('big_dataset_gioco.csv'):
        data = pd.read_csv('big_dataset_gioco.csv')
        print("Dataset caricato da Google Colab")

    else:
        # Controllo se il file esiste su GitHub e lo carico
        url = 'https://raw.githubusercontent.com/FabriceGhislain7/gdr-web-app/main/big_dataset_gioco.csv'
        data = pd.read_csv(url)
        print("Dataset caricato da GitHub")

except FileNotFoundError as e:
    print("Errore: file locale non trovato.")
    raise e
except URLError as e:
    print("Errore: problema di connessione o URL non valido.")
    raise e
except pd.errors.EmptyDataError as e:
    print("Errore: il file è vuoto o non contiene dati validi.")
    raise e
except Exception as e:
    print(f"Errore imprevisto: {e}")
    raise e

if data is not None:
    print("Dataset caricato correttamente.")
else:
    print("Impossibile caricare il dataset.")

# Visualizzazione del dataset
print("=" * 50)
data

Dataset caricato da GitHub
Dataset caricato correttamente.
==================================================

,player_id,nome,eta,genere,paese,città,mestiere,istruzione,soddisfazione,classe_personaggio,...,pausa_media_tra_sessioni,tipo_dispositivo,versione_app,numero_crash,latency_media,bug_rilevati,cluster_comportamentale,canale_acquisizione,campagne_risposta,profilo_social_integrato
0,1,Zoe,34.0,M,Angola,New Michaelbury,Exercise physiologist,Superiore,1,Ladro,...,35.0,Mobile,1.0,5,81,3,Casual,Referral,4,0
1,2,Debra,51.0,F,Brunei Darussalam,North Paulland,Ceramics designer,Università,9,Mago,...,10.5,Tablet,2.0,7,60,4,Casual,Organic,0,0
2,3,Vincent,58.0,F,Tajikistan,West Vanessafurt,Clothing/textile technologist,Università,3,Guerriero,...,66.7,Mobile,2.0,4,132,7,Casual,Referral,12,1
3,4,Kenneth,46.0,F,Netherlands Antilles,Davidville,Fish farm manager,Superiore,6,Ladro,...,17.3,Mobile,2.0,8,120,1,Casual,Pubblicità,7,0
4,5,Juan,23.0,NaN,Cayman Islands,Elliottport,"Administrator, local government",Superiore,3,Guerriero,...,23.7,Mobile,1.0,5,199,1,Spender,Pubblicità,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50495,50496,Joseph,22.0,M,Botswana,Kevinstad,Conference centre manager,Superiore,6,Mago,...,65.6,PC,1.0,4,64,4,Hardcore,Organic,9,0
50496,50497,Jennifer,50.0,F,Nepal,Lake Elizabethland,"Accountant, chartered public finance",Superiore,6,Mago,...,71.7,Mobile,1.2,6,49,8,Casual,Organic,1,0
50497,50498,Austin,44.0,F,Cyprus,Nicolemouth,Arts administrator,Superiore,10,Guerriero,...,38.0,Tablet,1.2,7,12,9,Hardcore,Organic,19,1
50498,50499,Colleen,35.0,F,Saint Helena,New Garrett,Careers information officer,Scuola Media,7,Ladro,...,65.4,PC,1.2,6,23,7,Casual,Referral,6,0
50499,50500,Daniel,21.0,F,Lithuania,South Jessica,"Production assistant, television",Superiore,1,Mago,...,69.1,PC,1.2,8,222,3,Hardcore,Organic,15,0

In [10]:
# Visualizzazione delle prime righe del dataset
print("Prime righe del dataset:")
print("=" * 50)
data.head()  # Puo prendere un argomaneto per un numero preciso di righe. data.head(20). By defaults vale 5

Prime righe del dataset:
==================================================

,player_id,nome,eta,genere,paese,città,mestiere,istruzione,soddisfazione,classe_personaggio,...,pausa_media_tra_sessioni,tipo_dispositivo,versione_app,numero_crash,latency_media,bug_rilevati,cluster_comportamentale,canale_acquisizione,campagne_risposta,profilo_social_integrato
0,1,Zoe,34.0,M,Angola,New Michaelbury,Exercise physiologist,Superiore,1,Ladro,...,35.0,Mobile,1.0,5,81,3,Casual,Referral,4,0
1,2,Debra,51.0,F,Brunei Darussalam,North Paulland,Ceramics designer,Università,9,Mago,...,10.5,Tablet,2.0,7,60,4,Casual,Organic,0,0
2,3,Vincent,58.0,F,Tajikistan,West Vanessafurt,Clothing/textile technologist,Università,3,Guerriero,...,66.7,Mobile,2.0,4,132,7,Casual,Referral,12,1
3,4,Kenneth,46.0,F,Netherlands Antilles,Davidville,Fish farm manager,Superiore,6,Ladro,...,17.3,Mobile,2.0,8,120,1,Casual,Pubblicità,7,0
4,5,Juan,23.0,NaN,Cayman Islands,Elliottport,"Administrator, local government",Superiore,3,Guerriero,...,23.7,Mobile,1.0,5,199,1,Spender,Pubblicità,13,0

In [9]:
# Visualizzazione delle ultime righe del dataset
print("Ultime righe del dataset:")
print("=" * 50)
data.tail()  # Puo prendere un argomaneto per un numero preciso di righe. data.head(20). By defaults vale 5

Ultime righe del dataset
==================================================

,player_id,nome,eta,genere,paese,città,mestiere,istruzione,soddisfazione,classe_personaggio,...,pausa_media_tra_sessioni,tipo_dispositivo,versione_app,numero_crash,latency_media,bug_rilevati,cluster_comportamentale,canale_acquisizione,campagne_risposta,profilo_social_integrato
50495,50496,Joseph,22.0,M,Botswana,Kevinstad,Conference centre manager,Superiore,6,Mago,...,65.6,PC,1.0,4,64,4,Hardcore,Organic,9,0
50496,50497,Jennifer,50.0,F,Nepal,Lake Elizabethland,"Accountant, chartered public finance",Superiore,6,Mago,...,71.7,Mobile,1.2,6,49,8,Casual,Organic,1,0
50497,50498,Austin,44.0,F,Cyprus,Nicolemouth,Arts administrator,Superiore,10,Guerriero,...,38.0,Tablet,1.2,7,12,9,Hardcore,Organic,19,1
50498,50499,Colleen,35.0,F,Saint Helena,New Garrett,Careers information officer,Scuola Media,7,Ladro,...,65.4,PC,1.2,6,23,7,Casual,Referral,6,0
50499,50500,Daniel,21.0,F,Lithuania,South Jessica,"Production assistant, television",Superiore,1,Mago,...,69.1,PC,1.2,8,222,3,Hardcore,Organic,15,0

In [13]:
# Ritorna le dimensioni del dataset, cioè, il numero di righe e di righe e di colonne.
print(f"The dataset contains '{data.shape[0]}' rows and '{data.shape[1]}' columns.")
print("=" * 50)
print(f"The dataset contains {data.size} elements.")
data.shape

The dataset contains '50500' rows and '40' columns.
==================================================
The dataset contains 2020000 elements.

(50500, 40)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50500 entries, 0 to 50499
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   player_id                   50500 non-null  int64
 1   nome                        50500 non-null  object
 2   eta                         47975 non-null  float64
 3   genere                      48985 non-null  object
 4   paese                       50500 non-null  object
 5   città                       50500 non-null  object
 6   mestiere                    50500 non-null  object
 7   istruzione                  48985 non-null  object
 8   soddisfazione               50500 non-null  int64
 9   classe_personaggio          48985 non-null  object
 10  livello                     50500 non-null  int64
 11  salute_media                47975 non-null  float64
 12  attacco_medio               47975 non-null  float64
 13  destrezza                   50500 non-null  int64
 14  oggetti_usati               50500 non-null  object
 15  numero_battaglie            50500 non-null  int64
 16  numero_vittorie             50500 non-null  int64
 17  numero_sconfitte            50500 non-null  int64
 18  tempo_totale_giocato        50500 non-null  int64
 19  crediti_attuali             47975 non-null  float64
 20  spesa_mensile               47975 non-null  float64
 21  numero_acquisti             50500 non-null  int64
 22  tipo_acquisti               50500 non-null  object
 23  abbonamento_attivo          50500 non-null  int64
 24  rimborso_totale             50500 non-null  int64
 25  giorni_attivi               50500 non-null  int64
 26  sessioni_giornaliere_medie  50500 non-null  float64
 27  durata_media_sessione       50500 non-null  int64
 28  ora_punta_login             50500 non-null  int64
 29  giorno_settimana_attivo     50500 non-null  object
 30  pausa_media_tra_sessioni    50500 non-null  float64
 31  tipo_dispositivo            50500 non-null  object
 32  versione_app                50500 non-null  float64
 33  numero_crash                50500 non-null  int64
 34  latency_media               50500 non-null  int64
 35  bug_rilevati                50500 non-null  int64
 36  cluster_comportamentale     50500 non-null  object
 37  canale_acquisizione         50500 non-null  object
 38  campagne_risposta           50500 non-null  int64
 39  profilo_social_integrato    50500 non-null  int64
dtypes: float64(8), int64(19), object(13)
memory usage: 15.4+ MB